#\u542F\u7528\u8C03\u8BD5\u6A21\u5F0F
debug: true
server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#   sqlserver
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #  url:  jdbc:sqlserver://39.105.135.92:1433;DatabaseName=hccpsp;integrated security=true
  #  username: sa
   # password: Xcvb0987
    #url: jdbc:sqlserver://112.232.156.237:9010;DatabaseName=djxmdb
 #   url: jdbc:sqlserver://zhuolutech.net:9010;DatabaseName=djxmdb
#    username: zhuolu
#    password: asdfg12345

 #   mysql
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: oracle.jdbc.OracleDriver
    username: cms
    password: zhuolu777
    url: jdbc:oracle:thin:@192.168.1.231:1521/zhuolu
    platform: oracle
    # \u4E0B\u9762\u4E3A\u8FDE\u63A5\u6C60\u7684\u8865\u5145\u8BBE\u7F6E\uFF0C\u5E94\u7528\u5230\u4E0A\u9762\u6240\u6709\u6570\u636E\u6E90\u4E2D
    # \u521D\u59CB\u5316\u5927\u5C0F\uFF0C\u6700\u5C0F\uFF0C\u6700\u5927
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
    maxWait: 60000
    # \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
    timeBetweenEvictionRunsMillis: 60000
    # \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # \u6253\u5F00PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899
#    filters: stat,wall,slf4j
    # \u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
