package generator.test;

import generator.CodeAutoGenerateDefault;
import generator.utils.FileUtil;

public class Test {

	public static void main(String[] args) {

		CodeAutoGenerateDefault.testCreate();

	}
}
